[0.6][Docker] Add env var to provide COURSIER_CACHE location. Fixes bug with the Docker build for non root (#1759) (#1784)
**PR Checklist**

- [x] A description of the changes is added to the description of this
PR.
- [x] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add
tests!
- [ ] If you've added or modified a feature, documentation in `docs` is
updated

**Description of changes**
Backport https://github.com/unitycatalog/unitycatalog/pull/1759

Added new env variable, set to write to the docker user's home cache
dir.

```
ENV COURSIER_CACHE=$HOME/.cache/coursier/v1
```

Without the addition of the cache location variable, the result is the
server starting up and exiting with code 1.

```
server-1 | Error: Unable to initialize main class io.unitycatalog.server.UnityCatalogServer
server-1 | Caused by: java.lang.NoClassDefFoundError: io/vertex/core/Verticle
server-1 exited with code 1
```

This resolves the bug I reported in
https://github.com/unitycatalog/unitycatalog/issues/1755.

**PR Checklist**

- [ ] A description of the changes is added to the description of this
PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add
tests!
- [ ] If you've added or modified a feature, documentation in `docs` is
updated

**Description of changes**

<!-- Please state what you've changed and how it might affect the users.
-->

Signed-off-by: Scott Haines <newfrontcreative@gmail.com>
Co-authored-by: Scott Haines <newfrontcreative@gmail.com>